### PR TITLE
feat: Time data type support - some additional fixes for timezone aware types

### LINKED ISSUE #929: validate row: TIMESTAMP WITH TIME ZONE fails for SQL Server and Teradata validations
Row validations of SQL Server to BigQuery and Teradata BigQuery fail.

See integrations test `test_row_validation_core_types_to_bigquery` in `test_sql_server.py` and `test_teradata.py`.

If you add col_tstz to the above tests and run them you will reproduce the error.

### LINKED ISSUE #1189: [TD to BQ] Unable to validate TIME fields
We are unable to run validations on tables containing fields with `TIME` datatype in TD vs BQ.

TD DDL:
```
CREATE TABLE time_field_bug (
    id INTEGER,
    time_field TIME(0)
);
```

BQ DDL
```
CREATE OR REPLACE TABLE dataset.time_field_bug (
    id INTEGER,
    time_field TIME
);
```

Error:
`[Teradata Database] [Error 3800] Datatype Mismatch in THEN/ELSE expression.`

### LINKED ISSUE #1202: sqlserver row hash validation fails if there is only one column to hash
Hi,

SQL Server row hash validation fails with `[SQL Server]The concat function requires 2 to 254 arguments. (189)` when presented with the command `data-validation validate row -sc sqlserver -tc bq -tbls=pso_data_validator.dvt_core_types -pk=id -hash=col_datetime`. Specifying `data-validation validate row -sc sqlserver -tc bq -tbls=pso_data_validator.dvt_core_types -pk=id -hash=col_datetime,col_tstz` works fine.

Examining the generated SQL with `--dry-run` shows `concat(t2.rstrip__ifnull__cast__col_datetime) AS concat__all  from t2)` being generated, while the same command on postgres shows `concat_ws('', t2.rstrip__ifnull__cast__col_datetime) AS concat__all  from t2`

Sundar Mudupalli

### PR DESCRIPTION
**Pull request by sundar-mudupalli-work**
Supports new data type [Time for Teradata and BigQuery](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1189)
Fixes other time zone aware types [MS SQL server](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/929) and [Teradata](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/929)
Fixes [single hash field issue for SQL Server](https://github.com/GoogleCloudPlatform/professional-services-data-validator/issues/1202)

Adds test case for Time data type

### CODE REVIEW

File: tests/resources/bigquery_test_tables.sql [hunk 1]
```diff
@@ -128,6 +128,16 @@ INSERT INTO `pso_data_validator`.`dvt_char_id` VALUES
 ('DVT4  ', 'Row 4'),
 ('DVT5  ', 'Row 5');
 
+DROP TABLE `pso_data_validator`.`dvt_time_table`;
+CREATE TABLE `pso_data_validator`.`dvt_time_table`
+(   id          INTEGER NOT NULL
+,   col_time  Time
```
Comment (helensilva14) [inline tests/resources/bigquery_test_tables.sql]:
```suggestion
,   col_time  TIME
```

File: tests/resources/bigquery_test_tables.sql [hunk 2]
```diff
@@ -128,6 +128,16 @@ INSERT INTO `pso_data_validator`.`dvt_char_id` VALUES
...
+) OPTIONS (description='Integration test table used to test Time Type');
```
Comment (helensilva14) [inline tests/resources/bigquery_test_tables.sql]:
```suggestion
) OPTIONS (description='Integration test table used to test Time data type');
```

File: tests/system/data_sources/test_sql_server.py [hunk 3]
```diff
@@ -408,7 +408,7 @@ def test_row_validation_core_types_to_bigquery():
             "-tbls=pso_data_validator.dvt_core_types",
             "--primary-keys=id",
             "--filter-status=fail",
-            "--hash=col_int8,col_int16,col_int32,col_int64,col_dec_20,col_dec_38,col_float32,col_float64,col_varchar_30,col_char_2,col_date,col_datetime",
+            "--hash=col_int8,col_int16,col_int32,col_int64,col_dec_20,col_dec_38,col_float32,col_float64,col_varchar_30,col_char_2,col_date,col_datetime,col_tstz",
```
Comment (helensilva14) [inline tests/system/data_sources/test_sql_server.py:410]: Since the column is being added here now, we need to remove the TODO statement from line 400 (I tried to comment directly on that line but I couldn’t bc it doesn’t have changes on this PR)

File: tests/system/data_sources/test_teradata.py [hunk 4]
```diff
@@ -387,7 +421,7 @@ def test_row_validation_core_types_to_bigquery():
     # TODO Change --hash option to include col_tstz when issue-929 is complete.
```
Comment (helensilva14) [inline tests/system/data_sources/test_teradata.py]: Since column is being added here now, we need to remove this TODO statement

File: third_party/ibis/ibis_addon/operations.py [hunk 5]
```diff
@@ -226,8 +228,13 @@ def strftime_mssql(translator, op):
         raise NotImplementedError(
             f"strftime format {pattern.value} not supported for SQL Server."
         )
-    result = sa.func.convert(sa.text("VARCHAR(32)"), arg, convert_style)
-    return result
+    arg_type = op.args[0].output_dtype
+    if (
+        hasattr(arg_type, "timezone") and arg_type.timezone
+    ):  # Timezone aware, issue #929 works for style 20 only convert adds a +00:00 which we must trim out
```
Comment (helensilva14) [inline third_party/ibis/ibis_addon/operations.py]: I'm confused with this comment 🤔

File: third_party/ibis/ibis_addon/operations.py [hunk 6]
```diff
@@ -507,7 +514,15 @@ def sa_cast_snowflake(t, op):
 
 
 def _sa_string_join(t, op):
-    return sa.func.concat(*map(t.translate, op.arg))
+    if (
+        len(op.arg) == 1
+    ):  # SQL Server concat errs on one argument (issue #1202), so casting to string - i.e. identity op
```
Comment (helensilva14) [inline third_party/ibis/ibis_addon/operations.py]: Also a bit confused with this comment, not sure if it needs to be removed or rephrased

**Review by helensilva14 — CHANGES_REQUESTED** [review]
Good job Sundar! I added some questions, linted the code, and pushed my coomit!

File: third_party/ibis/ibis_addon/operations.py (hunk 5 above)
Comment (sundar-mudupalli-work) [reply third_party/ibis/ibis_addon/operations.py]: Updated

File: third_party/ibis/ibis_addon/operations.py (hunk 6 above)
Comment (sundar-mudupalli-work) [reply third_party/ibis/ibis_addon/operations.py]: Updated

File: third_party/ibis/ibis_mssql/registry.py [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+
+    sa_table = get_sqla_table(ctx, table)
+
+    out_expr = get_col(sa_table, op)
+    out_expr.quote = t._quote_column_names
+
+    if op.output_dtype.is_timestamp():
+        timezone = op.output_dtype.timezone
+        if timezone is not None:
+            # Using literal_column on Oracle because the time zone string cannot be a bind.
```
Comment (helensilva14) [inline third_party/ibis/ibis_mssql/registry.py]:
```suggestion
            # Using literal_column on SQL Server because the time zone string cannot be a bind.
```

**Review by helensilva14 — APPROVED** [review]
LGTM! Just a minor comment fix suggested

File: tests/system/data_sources/test_teradata.py [hunk 8]
```diff
@@ -323,6 +323,40 @@ def test_column_validation_core_types_to_bigquery():
     assert len(df) == 0
 
 
+@mock.patch(
+    "data_validation.state_manager.StateManager.get_connection_config",
+    new=mock_get_connection_config,
+)
+def test_column_validation_time_table_to_bigquery():
+    # Unlike other temporal types, count is the only column validation supported for time
```
Comment (nj1973) [inline tests/system/data_sources/test_teradata.py:331]: Should we create a follow on issue to add support for min/max too?

File: third_party/ibis/ibis_addon/operations.py [hunk 9]
```diff
@@ -507,7 +513,15 @@ def sa_cast_snowflake(t, op):
 
 
 def _sa_string_join(t, op):
-    return sa.func.concat(*map(t.translate, op.arg))
+    if (
+        len(op.arg) == 1
+    ):  # SQL Server CONCAT errs when there is one column being hashed (issue #1202), renaming using type_coerce rather than CONCAT
```
Comment (nj1973) [inline third_party/ibis/ibis_addon/operations.py:518]: What a good idea, nice!

**Review by nj1973 — APPROVED** [review]
LGTM, great work.

File: third_party/ibis/ibis_teradata/registry.py [hunk 10]
```diff
@@ -114,7 +121,11 @@ def _table_column(t, op):
     alias = ctx.get_ref(table, search_parents=True)
     if alias is not None:
         quoted_name = f"{alias}.{quoted_name}"
-
+    if op.output_dtype.is_timestamp():
+        timezone = op.output_dtype.timezone
+        if timezone is not None:
+            timezone = "GMT" if timezone == "UTC" else timezone
```
Comment (nehanene15) [inline third_party/ibis/ibis_teradata/registry.py:127]: Is there a benefit to specifying GMT versus UTC in Teradata?

**Review by nehanene15 — APPROVED** [review]
Amazing work, LGTM! 
Just for my knowledge, do you know if we support TIME data types for Snowflake, Oracle, our other DBs?
